### ISSUE TITLE
NoSuchMethodError: void ModelCache$Entry$Cached.<init>(java.lang.Object, int, int)

### ISSUE THREAD

**Issue by gnawf** [Kodein-Framework/Kodein-DB#49]
Getting this exception when upgrading from 0.8.1 to 0.9.0 on Desktop JVM target

```
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: 'void org.kodein.db.model.cache.ModelCache$Entry$Cached.<init>(java.lang.Object, int, int)'
	at org.kodein.db.impl.model.cache.ModelCacheImpl$getOrRetrieveEntry$1.invoke(ModelCacheImpl.kt:133)
	at org.kodein.db.impl.model.cache.ModelCacheImpl$getOrRetrieveEntry$1.invoke(ModelCacheImpl.kt:123)
	at org.kodein.db.impl.model.cache.ModelCacheImpl$getOrRetrieveEntry$2.invoke(ModelCacheImpl.kt:291)
	at org.kodein.db.impl.model.cache.ModelCacheImpl$getOrRetrieveEntry$2.invoke(ModelCacheImpl.kt:143)
	at org.kodein.db.impl.model.cache.ModelCacheImpl.getOrRetrieveEntry(ModelCacheImpl.kt:123)
	at org.kodein.db.impl.model.cache.ModelCacheImpl.getOrRetrieveEntry(ModelCacheImpl.kt:143)
	at org.kodein.db.impl.model.cache.CachedModelCursor.model(CachedModelCursor.kt:23)
	at org.kodein.db.impl.CursorImpl.model(CursorImpl.kt:13)
	at org.kodein.db.CursorKt$asModelSequence$$inlined$asSequence$1.invokeSuspend(Cursor.kt:47)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:140)
	at kotlin.sequences.TakeSequence$iterator$1.hasNext(Sequences.kt:421)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
```

Code was

```kotlin
        return db
            .find<Obj>()
            .use { cursor ->
                cursor.asModelSequence(reverse = true)
                    .toList()
            }
```

Also, do a new release? The functions in commit https://github.com/Kodein-Framework/Kodein-DB/commit/f2909cde1c5e3ce7d747cb417804fe784020e9c4 aren't available in 0.9.0-beta
